imports:
    - { resource: "@PimcoreAiBundle/Resources/config/packages/doctrine_migrations.yaml" }

pimcore:
    documents:
        editables:
            map:
                ai_wysiwyg: Instride\Bundle\PimcoreAiBundle\Model\Document\Editable\AiWysiwyg
    objects:
        class_definitions:
            data:
                map:
                  aiWysiwyg: Instride\Bundle\PimcoreAiBundle\Model\DataObject\ClassDefinition\Data\AiWysiwyg
