pimcore_ai_tools:
    providers:
        open_ai:
            api_key: '%env(OPEN_AI_API_KEY)%'
#        midjourney:
#            channel_id: '%env(MIDJOURNEY_CHANNEL_ID)%'
#            auth_token: '%env(MIDJOURNEY_AUTH_TOKEN)%'
    editables: ~
    frontend: ~
