pimcore_ai_sync_editables:
    path: /sync-editables
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\ConfigurationController::syncEditablesAction }
    methods:
        - POST

pimcore_ai_sync_objects:
    path: /sync-objects
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\ConfigurationController::syncObjectsAction }
    methods:
        - POST


pimcore_ai_settings_editable_configuration:
    path: /settings/editable-configuration
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\SettingsController::editableConfigurationAction }
    methods:
        - POST

pimcore_ai_settings_object_configuration:
    path: /settings/object-configuration
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\SettingsController::objectConfigurationAction }
    methods:
        - POST


pimcore_ai_text_create:
    path: /text-create
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\PromptController::textCreationAction }
    methods: [GET, POST]

pimcore_ai_text_correction:
    path: /text-correct
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\PromptController::textCorrectionAction }
    methods:
        - POST

pimcore_ai_text_optimization:
    path: /text-optimize
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\PromptController::textOptimizationAction }
    methods: [GET, POST]
