pimcore_ai_settings_load_defaults:
    path: /load-defaults
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\SettingsController::loadDefaultsAction }
    methods:
        - POST

pimcore_ai_settings_save_defaults:
    path: /save-defaults
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\SettingsController::saveDefaultsAction }
    methods:
        - POST

pimcore_ai_settings_sync_editables:
    path: /sync-editables
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\SettingsController::syncEditablesAction }
    methods:
        - POST

pimcore_ai_settings_sync_objects:
    path: /sync-objects
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\SettingsController::syncObjectsAction }
    methods:
        - POST

pimcore_ai_settings_editable_configuration:
    path: /editable-configuration
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\SettingsController::editableConfigurationAction }
    methods:
        - POST

pimcore_ai_settings_object_configuration:
    path: /object-configuration
    defaults: { _controller: Instride\Bundle\PimcoreAiBundle\Controller\Admin\SettingsController::objectConfigurationAction }
    methods:
        - POST
