services:

    # Open AI Provider
    Instride\Bundle\PimcoreAiBundle\Provider\OpenAiProvider:
        tags:
            - { name: pimcore_ai.provider_type, alias: open_ai_provider, type: open_ai }
        arguments:
            - '%pimcore_ai.open_ai.api_key%'

    # Midjourney Provider
    Instride\Bundle\PimcoreAiBundle\Provider\MidjourneyProvider:
        tags:
            - { name: pimcore_ai.provider_type, alias: midjourney_provider, type: midjourney }
        arguments:
            - '%pimcore_ai.midjourney.channel_id%'
            - '%pimcore_ai.midjourney.auth_key%'
