services:

    # Open AI Provider
    pimcore_ai.provider.open_ai:
        class: Instride\Bundle\PimcoreAiBundle\Provider\OpenAiProvider
        tags:
            - { name: 'pimcore_ai.provider', key: 'open_ai' }
        arguments:
            - '%pimcore_ai.providers.open_ai.api_key%'

    # Midjourney Provider
    pimcore_ai.provider.midjourney:
        class: Instride\Bundle\PimcoreAiBundle\Provider\MidjourneyProvider
        tags:
            - { name: 'pimcore_ai.provider', key: 'midjourney' }
        arguments:
            - '%pimcore_ai.providers.midjourney.channel_id%'
            - '%pimcore_ai.providers.midjourney.auth_key%'
