services:

    # Configuration Service
    Instride\Bundle\PimcoreAiBundle\Services\ConfigurationService:
        tags:
            - { name: pimcore_ai.services.configuration }
        arguments:
          [ '@Instride\Bundle\PimcoreAiBundle\Locator\ProviderLocator' ]

    # Prompt Service
    Instride\Bundle\PimcoreAiBundle\Services\PromptService:
        tags:
            - { name: pimcore_ai.services.ai }
