services:

    # Provider Locator
    Instride\Bundle\PimcoreAiBundle\Locator\ProviderLocator:
        arguments:
            $locator: '@pimcore_ai.provider_locator'
        tags: ['controller.service_arguments']

    pimcore_ai.provider_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                OpenAi: '@pimcore_ai.provider.open_ai'
                Midjourney: '@pimcore_ai.provider.midjourney'
        tags: ['container.service_locator']
