pimcore_ai_tools_translation:
    path: /translate/{objectId}/{className}/{fieldNames}/{toLanguage}
    defaults: { _controller: Instride\Bundle\PimcoreAiToolsBundle\Controller\TranslationController::translateAction }
    methods:
        - POST

pimcore_ai_tools_translation_all:
    path: /translate-all/{objectId}/{className}/{fieldNames}/{toLanguage}
    defaults: { _controller: Instride\Bundle\PimcoreAiToolsBundle\Controller\TranslationController::translateAllAction }
    methods:
        - POST

#pimcore_ai_tools_translate_picture:
#    path:/translate-picture/{objectId}/{toLanguage}
#    defaults: { _controller: Instride\Bundle\PimcoreAiToolsBundle\Controller\TranslationController::translatePictureAction }
#    methods:
#        - POST
